basePath: /api/v1
definitions:
  create.request:
    properties:
      name:
        type: string
      patronymic:
        type: string
      surname:
        type: string
    required:
    - name
    - surname
    type: object
  delete.request:
    properties:
      name:
        type: string
      patronymic:
        type: string
      surname:
        type: string
    required:
    - name
    - surname
    type: object
  get.response:
    properties:
      data:
        items:
          $ref: '#/definitions/get.responseRecord'
        type: array
      paging:
        properties:
          next:
            type: string
          previous:
            type: string
        type: object
    type: object
  get.responseRecord:
    properties:
      age:
        type: integer
      name:
        type: string
      nationality:
        type: string
      patronymic:
        type: string
      sex:
        type: string
      surname:
        type: string
    type: object
  update.request:
    properties:
      age:
        maximum: 130
        minimum: 0
        type: integer
      name:
        type: string
      nationality:
        type: string
      patronymic:
        type: string
      sex:
        type: string
      surname:
        type: string
    required:
    - name
    - surname
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8081
info:
  contact: {}
  description: Сервис, который будет получать ФИО, из открытых апи обогащать ответ
    наиболее вероятными возрастом, полом и национальностью.
  title: Enricher
  version: "1.0"
paths:
  /records/create:
    post:
      consumes:
      - application/json
      description: Создание новой записи на обогащение
      parameters:
      - description: ФИО
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/create.request'
      produces:
      - application/json
      responses:
        "200":
          description: Запись успешно создана
      summary: Новая запись
      tags:
      - records
  /records/delete:
    post:
      consumes:
      - application/json
      description: Удаление записи о ФИО
      parameters:
      - description: ФИО
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/delete.request'
      produces:
      - application/json
      responses:
        "200":
          description: Запись успешно удалена
      summary: Удалить запись
      tags:
      - records
  /records/get:
    get:
      consumes:
      - application/json
      description: Получение данных с различными фильтрами и пагинацией
      parameters:
      - description: name =
        in: query
        name: name
        type: string
      - description: surname =
        in: query
        name: surname
        type: string
      - description: patronymic =
        in: query
        name: patronymic
        type: string
      - description: age >=
        in: query
        name: age[gte]
        type: integer
      - description: age <=
        in: query
        name: age[lte]
        type: integer
      - description: sex =
        in: query
        name: sex
        type: string
      - description: nationality =
        in: query
        name: nationality
        type: string
      - description: limit =
        in: query
        name: limit
        type: integer
      - description: after =
        in: query
        name: after
        type: string
      - description: before =
        in: query
        name: before
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: resp
          schema:
            $ref: '#/definitions/get.response'
      summary: Получение данных
      tags:
      - records
  /records/update:
    post:
      consumes:
      - application/json
      description: Обновление записи для ФИО
      parameters:
      - description: ФИО
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/update.request'
      produces:
      - application/json
      responses:
        "200":
          description: Запись успешно изменена
      summary: Обновить запись
      tags:
      - records
swagger: "2.0"
